// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSp7IDLScAOKpkRxtv1fbpLRmZEiMc2Ms',
    appId: '1:1088629577763:android:d27516d5a25cb92533b996',
    messagingSenderId: '1088629577763',
    projectId: 'kotlin-firebase-e4212',
    databaseURL: 'https://kotlin-firebase-e4212.firebaseio.com',
    storageBucket: 'kotlin-firebase-e4212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARhSfb-F6UI2p6io_R8xxgMy7WQs03fCI',
    appId: '1:1088629577763:ios:dc9a9eb44da706d433b996',
    messagingSenderId: '1088629577763',
    projectId: 'kotlin-firebase-e4212',
    databaseURL: 'https://kotlin-firebase-e4212.firebaseio.com',
    storageBucket: 'kotlin-firebase-e4212.appspot.com',
    iosBundleId: 'com.wtfrupesh.flutterNotification',
  );
}
